// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBet4jexkg16UYGUUt3_tFkrXKHvMS1EEo',
    appId: '1:70908528766:web:8b7e45678350d2dd1b302f',
    messagingSenderId: '70908528766',
    projectId: 'flyin-28c1d',
    authDomain: 'flyin-28c1d.firebaseapp.com',
    databaseURL: 'https://flyin-28c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flyin-28c1d.appspot.com',
    measurementId: 'G-BKPTFM4Z6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh08pxDWtxf8833ftuglrwVwCKxA_Pao0',
    appId: '1:70908528766:android:15f24ead7f152fad1b302f',
    messagingSenderId: '70908528766',
    projectId: 'flyin-28c1d',
    databaseURL: 'https://flyin-28c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flyin-28c1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJwuRmFy1uzE1yNLe6Ztuhq8iET9z8z4c',
    appId: '1:70908528766:ios:3f3f5f261ea96d6a1b302f',
    messagingSenderId: '70908528766',
    projectId: 'flyin-28c1d',
    databaseURL: 'https://flyin-28c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flyin-28c1d.appspot.com',
    iosBundleId: 'com.example.flyinBlackcoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJwuRmFy1uzE1yNLe6Ztuhq8iET9z8z4c',
    appId: '1:70908528766:ios:3bb12feff8b29b411b302f',
    messagingSenderId: '70908528766',
    projectId: 'flyin-28c1d',
    databaseURL: 'https://flyin-28c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flyin-28c1d.appspot.com',
    iosBundleId: 'com.example.flyinBlackcoffer.RunnerTests',
  );
}
